"""Single source of truth for the runtime environment MTR runs tools in.

Everything that launches ``edps`` / ``pyesorex`` / ``scopesim`` (the GUI's
subprocess launcher, the ``mtr-cli`` orchestrated run, and the ``mtr-exec`` /
``mtr-shell`` direct-access commands) resolves its environment here, so the
manual and orchestrated paths are guaranteed identical.

For the ``default`` runner the values are *derived from* :mod:`paths` — no
hand-written ``.env`` is needed.  An ``.env`` generated by the Install tab, if
present, is layered on top purely as an optional override.  ``native`` inherits
the parent environment unchanged (tools are expected on ``PATH``); for
``docker`` / ``podman`` the environment lives inside the container, so callers
wrap commands with ``runner_prefix()`` instead of injecting env vars.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from . import paths


def resolve_runtime_env(runner: str = "default") -> dict[str, str]:
    """Return the environment dict for spawning pipeline tools under *runner*.

    For ``default``, derives ``PYTHONPATH`` / recipe dirs / instrument-packages
    path from :mod:`paths`, prepends the MTR venv ``bin/`` to ``PATH`` (so
    ``edps`` / ``pyesorex`` resolve to the venv copies), and layers an optional
    Install-tab ``.env`` on top.  For other runners, returns the parent
    environment (plus ``PYTHONUNBUFFERED``) unchanged.
    """
    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"

    if runner != "default":
        return env

    pipe = paths.pipeline_dir()
    sims = paths.simulations_dir()
    # pymetis is editable-installed, but the src/ entry keeps EDPS/pyesorex
    # subprocesses resolving the same clone copy regardless of venv layout.
    env["PYTHONPATH"] = f"{sims}:{pipe}/metisp/pymetis/src/"
    env["PYCPL_RECIPE_DIR"] = f"{pipe}/metisp/pyrecipes/"
    env["PYESOREX_PLUGIN_DIR"] = f"{pipe}/metisp/pyrecipes/"
    env["PYESOREX_MSG_LEVEL"] = "debug"
    env["PYESOREX_LOG_LEVEL"] = "debug"
    # So ScopeSim resolves the instrument packages in a bare `python` session.
    env["METIS_INST_PKGS"] = str(paths.inst_pkgs_dir())

    venv_bin = str(Path(sys.executable).parent)
    env["PATH"] = venv_bin + os.pathsep + env.get("PATH", "")

    # Optional override: an Install-tab .env wins over the derived defaults.
    env_file = paths.env_file()
    if env_file.exists():
        from dotenv import dotenv_values
        env.update({k: v for k, v in dotenv_values(env_file).items()
                    if v is not None})

    return env


def runner_prefix(runner: str, container: str | None,
                  interactive: bool = False) -> list[str]:
    """Return the command prefix that targets *runner*.

    Empty for ``default`` / ``native`` (run locally); for ``docker`` / ``podman``
    returns ``[runner, "exec", "-i"/"-it", container]`` so a command runs inside
    the container.  Raises ``ValueError`` if a container runner has no container.
    """
    if runner in ("docker", "podman"):
        if not container:
            raise ValueError(
                f"--runner {runner} requires --container NAME "
                "(or the METIS_CONTAINER env var)."
            )
        return [runner, "exec", "-it" if interactive else "-i", container]
    return []
